#!/bin/bash
checkEnv () {
    if test ! -d "./body"; then
          mkdir body
    fi

    if test ! -d "./decoration"; then
          mkdir decoration
    fi

		if test ! -d "./eyes"; then
          mkdir eyes
    fi

		if test ! -d "./feet"; then
					mkdir feet
		fi

    if test ! -d "./hands"; then
          mkdir hands
    fi

    if test ! -d "./marking"; then
          mkdir marking
    fi

		if test ! -d "./0.6_skins"; then
          mkdir 0.6_skins
    fi
}

stripBody() {
    cp $f "./body"

    cd "./body"

    convert $f -crop 96x96+0+0 output.png
    convert $f -crop 96x96+96+0 output2.png

    montage -geometry +1+1 output2.png output.png -background none output3.png

    mogrify -extent 384x96+0+0 -background none output3.png

    cp output3.png $f

    rm output.png output2.png output3.png

    cd ..
}

stripEyes() {
    cp $f "./eyes"

    cd "./eyes"

    convert $f -crop 576x32+64+96 output.png

    cp output.png $f

    rm output.png

    cd ..
}

stripFeet() {
    cp $f "./feet"

    cd "./feet"

    convert $f -crop 64x64+192+32 output.png

    cp output.png $f

    rm output.png

    cd ..
}

stripHands() {
    cp $f "./hands"

    cd "./hands"

    convert $f -crop 64x32+192+0 output.png

    cp output.png $f

    rm output.png

    cd ..
}

createSkin() {
	name=$(echo $f | cut -f 1 -d '.')
	touch "$name.skn"

	echo "{"skin": {
		"body": {
			"filename": "$name",
			"custom_colors": "false"
		},
		"hands": {
			"filename": "$name",
			"custom_colors": "false"
		},
		"feet": {
			"filename": "$name",
			"custom_colors": "false"
		},
		"eyes": {
			"filename": "$name",
			"custom_colors": "false"
		}}
	}" >> $name.skn
}

deletSkin() {
	rm $f
}

checkEnv

for f in *.png; do
	stripBody
	stripEyes
	stripFeet
	stripHands
	createSkin
	#deletSkin
done
