#!/bin/bash
checkEnv () {
    if test ! -d "./body"; then
          mkdir body
    fi

    if test ! -d "./decoration"; then
          mkdir decoration
    fi

		if test ! -d "./eyes"; then
          mkdir eyes
    fi

		if test ! -d "./feet"; then
					mkdir feet
		fi

    if test ! -d "./hands"; then
          mkdir hands
    fi

    if test ! -d "./marking"; then
          mkdir marking
    fi

		if test ! -d "./0.6_skins"; then
          mkdir 0.6_skins
    fi
}

stripBody() {
    cp $f "./body"

    cd "./body"

    convert $f -crop 96x96+0+0 -resize 128x128^ output.png
    convert $f -crop 96x96+96+0 -resize 128x128^ output2.png

    montage -geometry +1+1 output2.png output.png -background none output3.png

    mogrify -extent 256x256+0+0 -background none output3.png

    cp output3.png $f

    rm output.png output2.png output3.png

    cd ..
}

stripEyes() {
    cp $f "./eyes"

    cd "./eyes"

    #Normal Eye
    convert $f -crop 24x32+64+96 normaleye.png
    convert $f -crop 8x32+64+96 space.png

    convert space.png normaleye.png +append -background none lefteye.png

    convert -flop lefteye.png righteye.png

    convert lefteye.png righteye.png +append -background none normal.png

    #Angry Eye
    convert $f -crop 24x32+96+96 angryeye.png

    convert space.png angryeye.png +append -background none lefteye.png

    convert -flop lefteye.png righteye.png

    convert lefteye.png righteye.png +append -background none angry.png

    #Hurt Eye
    convert $f -crop 24x32+128+96 hurteye.png

    convert space.png hurteye.png +append lefteye.png

    convert -flop lefteye.png righteye.png

    convert lefteye.png righteye.png +append -background none hurt.png

    #Happy Eye
    convert $f -crop 24x32+160+96 happyeye.png

    convert space.png happyeye.png +append -background none lefteye.png

    convert -flop lefteye.png righteye.png

    convert lefteye.png righteye.png +append -background none happy.png

    #Ninja Eye
    convert $f -crop 24x32+224+96 ninjaeye.png

    convert space.png ninjaeye.png +append -background none lefteye.png

    convert -flop lefteye.png righteye.png

    convert lefteye.png righteye.png +append -background none ninja.png

    #Merge Eyes
    convert normal.png angry.png +append -background none output3.png
    convert hurt.png happy.png +append -background none output4.png
    convert ninja.png space.png +append -background none output5.png

    convert output3.png output4.png -append -background none output6.png
    convert output6.png output5.png -append -background none output7.png
    convert output7.png space.png -append -background none output8.png

    convert output8.png -resize 120x120^ output9.png

    cp output9.png $f

    #Clean Up
    rm normaleye.png normal.png angryeye.png angry.png hurteye.png hurt.png happyeye.png happy.png ninjaeye.png ninja.png lefteye.png righteye.png space.png output1.png output2.png output3.png output4.png output5.png output6.png output7.png output8.png output9.png

    cd ..
}

stripFeet() {
    cp $f "./feet"

    cd "./feet"

    convert $f -crop 32x32+208+32 -resize 64x64^ output.png
		convert $f -crop 32x32+208+64 -resize 64x64^ output2.png

		convert output.png output2.png +append output3.png

    cp output3.png $f

    rm output.png output2.png output3.png

    cd ..
}

stripHands() {
    cp $f "./hands"

    cd "./hands"

    convert $f -crop 64x32+192+0 -resize 128x64^ output.png

    cp output.png $f

    rm output.png

    cd ..
}

createSkin() {
	name=$(echo $f | cut -f 1 -d '.')

	echo "{"skin": {
		"body": {
			"filename": "$name",
			"custom_colors": "false"
		},
		"hands": {
			"filename": "$name",
			"custom_colors": "false"
		},
		"feet": {
			"filename": "$name",
			"custom_colors": "false"
		},
		"eyes": {
			"filename": "$name",
			"custom_colors": "false"
		}}
	}" >> $name.json
}

moveskin() {
    cp $f "./0.6 skins"
}

deletSkin() {
    rm $f
}

checkEnv

for f in *.png; do
    stripBody
    stripEyes
    stripFeet
    stripHands
    createSkin
#    moveskin
#    deletSkin
done
